#
# ENV VARIABLES
#
env:
  ### Shared variables
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  DEVELOCITY_TOKEN: VAULT[development/kv/data/develocity data.token]
  DEVELOCITY_ACCESS_KEY: develocity.sonar.build=${DEVELOCITY_TOKEN}

  GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]

  ### Project variables
  DEPLOY_PULL_REQUEST: true
  CIRRUS_SHELL: bash

#
# RE-USABLE CONFIGS
#
container_definition_11: &CONTAINER_DEFINITION_11
  dockerfile: integrationTests/docker/Dockerfile_java11
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  region: eu-central-1
  namespace: default

container_definition_17: &CONTAINER_DEFINITION_17
  dockerfile: integrationTests/docker/Dockerfile_java17
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  region: eu-central-1
  namespace: default

win_vm_definition: &WINDOWS_VM_DEFINITION
  experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
  platform: windows
  region: eu-central-1
  type: c5.4xlarge # 3.6 GHz (3.9GHz single core) Intel Xeon Scalable Processor, 16 vCPU, 32 GiB Memory

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_RELEASE == "" && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

log_develocity_url_script: &log_develocity_url_script |
  echo "Develocity URL: https://develocity.sonar.build/scans?search.publicHostnames=cirrus-ci-task-${CIRRUS_TASK_ID}"

build_task:
  only_if: $CIRRUS_RELEASE == "" && $CIRRUS_TAG == ""
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 6G
  env:
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: VAULT[development/kv/data/next data.url]
    ORG_GRADLE_PROJECT_signingKey: VAULT[development/kv/data/sign data.key]
    ORG_GRADLE_PROJECT_signingPassword: VAULT[development/kv/data/sign data.passphrase]
    ORG_GRADLE_PROJECT_signingKeyId: VAULT[development/kv/data/sign data.key_id]
  gradle_cache:
    folder: ~/.gradle/caches
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script:
    - *log_develocity_url_script
    - source cirrus-env BUILD
    - source cirrus/define-gradle.sh
    - mvn -f property-dump-plugin/pom.xml -B install
    - regular_gradle_build_deploy_analyze -Dsonar.sca.exclusions="integrationTests/src/test/resources/**,src/test/projects/**"
  on_failure:
    reports_artifacts:
      path: "**/build/reports/**/*"
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit

sonar_shadow_scan_and_issue_replication_task:
  depends_on:
    - build
  # Only run when triggered by the cirrus-ci cron job named "nightly"
  only_if: $CIRRUS_CRON == "nightly"
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 6G
  env:
    SONAR_PROJECT_KEY: "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin"
    SHADOW_ORGANIZATION: "sonarsource"
    SHADOW_PROJECT_KEY: "SonarSource_sonar-scanner-gradle"
    # to replicate issue states from next
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: VAULT[development/kv/data/next data.url]
    matrix:
      - name: "sonarcloud.io"
        SHADOW_SONAR_TOKEN: VAULT[development/kv/data/sonarcloud data.token]
        SHADOW_SONAR_HOST_URL: "https://sonarcloud.io"
      - name: "sonarqube.us"
        SHADOW_SONAR_TOKEN: VAULT[development/kv/data/sonarqube-us data.token]
        SHADOW_SONAR_HOST_URL: "https://sonarqube.us"
  gradle_cache:
    folder: ~/.gradle/caches
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  build_and_shadow_scan_script:
    - *log_develocity_url_script
    - source cirrus-env BUILD
    - source cirrus/define-gradle.sh
    - ./shadow-scan-and-issue-replication.sh -Dsonar.sca.exclusions="integrationTests/src/test/resources/**,src/test/projects/**"

build_win_task:
  only_if: $CIRRUS_RELEASE == "" && $CIRRUS_TAG == ""
  ec2_instance:
    image: base-windows-jdk17-v*
    <<: *WINDOWS_VM_DEFINITION
  gradle_cache:
    folder: ~/.gradle/caches
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  java_download_cache:
    folder: ${CIRRUS_WORKING_DIR}/.java_download_cache
  build_script:
    - *log_develocity_url_script
    - source cirrus-env BUILD
    - ./gradlew --no-daemon --info --stacktrace --console plain build -DbuildNumber="$BUILD_NUMBER"

qa_win_task:
  env:
    GRADLE_VERSION: 9.1.0
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  ec2_instance:
    image: base-windows-jdk17-v*
    <<: *WINDOWS_VM_DEFINITION
  gradle_cache:
    folder: ~/.gradle/caches
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  java_download_cache:
    folder: ${CIRRUS_WORKING_DIR}/.java_download_cache
  build_script:
    - *log_develocity_url_script
    - source cirrus-env QA
    - ./cirrus/cirrus-qa.sh

validate_external_contributor_build_task:
  only_if: $CIRRUS_RELEASE == "" && $CIRRUS_TAG == ""
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script: |
    unset ARTIFACTORY_URL && \
    unset ARTIFACTORY_PRIVATE_USERNAME && \
    unset ARTIFACTORY_PRIVATE_PASSWORD && \
    unset ARTIFACTORY_ACCESS_TOKEN && \
    ./gradlew --refresh-dependencies clean assemble testClasses
  on_failure:
    reports_artifacts:
      path: "**/build/reports/**/*"
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit

gradle_qa_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 2
    memory: 4G
  env:
    matrix:
      - GRADLE_VERSION: 9.2.0
      - GRADLE_VERSION: 9.1.0
      - GRADLE_VERSION: 9.0.0
      - GRADLE_VERSION: 8.13
      - GRADLE_VERSION: 8.13
        ANDROID_GRADLE_VERSION: 8.13.0
      - GRADLE_VERSION: 8.4
      - GRADLE_VERSION: 8.4
        ANDROID_GRADLE_VERSION: 8.3.0
      - GRADLE_VERSION: 8.3
      - GRADLE_VERSION: 8.0
      - GRADLE_VERSION: 7.6.4
      - GRADLE_VERSION: 7.5.1
        ANDROID_GRADLE_VERSION: 7.1.0
  script:
    - *log_develocity_url_script
    - ./cirrus/cirrus-qa.sh

gradle_qa_java11_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION_11
    cpu: 2
    memory: 2G
  env:
    matrix:
      - GRADLE_VERSION: 7.5.1
        ANDROID_GRADLE_VERSION: 7.1.0
      - GRADLE_VERSION: 6.8.3
        ANDROID_GRADLE_VERSION: 4.2.0
      - GRADLE_VERSION: 5.6.4
        ANDROID_GRADLE_VERSION: 3.5.4
  script:
    - *log_develocity_url_script
    - ./cirrus/cirrus-qa.sh

promote_task:
  depends_on:
    - build
    - sonar_shadow_scan_and_issue_replication
    - build_win
    - qa_win
    - validate_external_contributor_build
    - gradle_qa
    - gradle_qa_java11
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1
    memory: 2G
  env:
    ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
  script: cirrus_promote_gradle

# This task is only executed manually in Cirrus-CI UI to validate the release process.
# It does not publish the artifacts matching the current build but the latest build of the master branch.
# The task only tests the configuration and logic of the release process using the latest promoted (and signed) build from the master branch.
# Once executed, the logs contain the json request sent during the publication, so we can manually check the content
# that will be sent to Gradle Plugin Portal. And we really send the request to the Gradle Plugin Portal in validation mode,
# not to publish the artifacts but to check the authentication mechanism and the validity of the metadata.
simulate_and_validate_release_to_plugin_portal_task:
  trigger_type: manual
  skip: true
  depends_on:
    - promote
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    ORG_GRADLE_PROJECT_signingKey: VAULT[development/kv/data/sign data.key]
    ORG_GRADLE_PROJECT_signingPassword: VAULT[development/kv/data/sign data.passphrase]
    ORG_GRADLE_PROJECT_signingKeyId: VAULT[development/kv/data/sign data.key_id]
    GRADLE_PUBLISH_KEY: VAULT[development/kv/data/gradle/publish data.key]
    GRADLE_PUBLISH_SECRET: VAULT[development/kv/data/gradle/publish data.secret]
    ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  # We force CIRRUS_TAG to be the latest build version of the master branch (repox: sonarsource-public-builds) to ensure the artifacts are signed
  # The publish simulation and validation will use those artifacts to check if the release logic is valid
  script: |
    export CIRRUS_TAG="$(cirrus/latest-repox-master-builds-plugin-version.sh)"
    source cirrus/prepare-release-configuration-from-cirrus-tag.sh
    ./gradlew \
      --info \
      --stacktrace \
      --console plain \
      -DbuildNumber="${BUILD_NUMBER}" \
      -Dsimulate-publish=true \
      downloadMavenArtifactsAndPublishToGradlePluginPortal
    ./gradlew \
      --info \
      --stacktrace \
      --console plain \
      -DbuildNumber="${BUILD_NUMBER}" \
      -Dvalidate-publish=true \
      downloadMavenArtifactsAndPublishToGradlePluginPortal

release_plugin_to_repox_task:
  only_if: $CIRRUS_PRERELEASE != "true" && $CIRRUS_RELEASE != "" && $CIRRUS_TAG != ""
  stateful: 'true'
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  script: |
    source cirrus/prepare-release-configuration-from-cirrus-tag.sh
    jfrog rt bpr \
      --url "${ARTIFACTORY_URL}" \
      --access-token "${ARTIFACTORY_ACCESS_TOKEN}" \
      --status released \
      "${CIRRUS_REPO_NAME}" "${BUILD_NUMBER}" sonarsource-public-releases

release_plugin_to_gradle_plugin_portal_task:
  only_if: $CIRRUS_PRERELEASE != "true" && $CIRRUS_RELEASE != "" && $CIRRUS_TAG != ""
  depends_on:
    - release_plugin_to_repox
  stateful: 'true'
  eks_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 1.5
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    ORG_GRADLE_PROJECT_signingKey: VAULT[development/kv/data/sign data.key]
    ORG_GRADLE_PROJECT_signingPassword: VAULT[development/kv/data/sign data.passphrase]
    ORG_GRADLE_PROJECT_signingKeyId: VAULT[development/kv/data/sign data.key_id]
    GRADLE_PUBLISH_KEY: VAULT[development/kv/data/gradle/publish data.key]
    GRADLE_PUBLISH_SECRET: VAULT[development/kv/data/gradle/publish data.secret]
    ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  script: |
    source cirrus/prepare-release-configuration-from-cirrus-tag.sh
    ./gradlew \
      --info \
      --stacktrace \
      --console plain \
      -DbuildNumber="${BUILD_NUMBER}" \
      downloadMavenArtifactsAndPublishToGradlePluginPortal
