name: QA Gradle
description: Run QA tests with different Gradle versions

inputs:
  gradle-version:
    required: true
  android-gradle-version:
    required: true
  sonar-runtime-version:
    required: false

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # 3.5.1
      with:
        version: 2025.12.10
    - name: Get Vault secrets
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/github/token/licenses-ro token | GITHUB_TOKEN;
          development/artifactory/token/{REPO_OWNER_NAME_DASH}-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;
    - name: Configure Maven
      uses: SonarSource/ci-github-actions/config-maven@v1
      with:
        artifactory-reader-role: private-reader
        working-directory: integrationTests
      env:
        GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}
        ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
    - name: Run QA
      env:
        GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}
        ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
        SONARSOURCE_QA: true
        GRADLE_VERSION: ${{ inputs.gradle-version }}
        ANDROID_GRADLE_VERSION: ${{ inputs.android-gradle-version }}
        SONAR_RUNTIME_VERSION: ${{ inputs.sonar-runtime-version }}
      shell: bash
      run: |
        source ./.github/scripts/set-version-from-build-number.sh
        mvn -f property-dump-plugin/pom.xml --batch-mode install
        cd integrationTests
        mvn --errors --batch-mode --no-transfer-progress org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false
        mvn --errors --batch-mode --no-transfer-progress clean verify -Dgradle.version="${GRADLE_VERSION}" -DandroidGradle.version="${ANDROID_GRADLE_VERSION}" -Dsonar.runtimeVersion="${SONAR_RUNTIME_VERSION}"
