#!/usr/bin/env python3
import hashlib
import http.client
import re
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ElementTree
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path

REPOSITORIES = {
    "Maven Central": "https://repo1.maven.org/maven2",
    "Gradle Plugin Portal": "https://plugins.gradle.org/m2",
    "Google Maven": "https://dl.google.com/dl/android/maven2",
}
METADATA_PATH = (
    Path(__file__).resolve().parent.parent / "gradle" / "verification-metadata.xml"
)
GENERATED_ORIGIN = "Generated by Gradle"
SHA256_PATTERN = re.compile(r"[0-9a-fA-F]{64}")


@dataclass(frozen=True)
class ArtifactChecksum:
    group: str
    name: str
    version: str
    artifact_name: str
    expected_sha256: str

    @property
    def coordinate(self) -> str:
        return f"{self.group}:{self.name}:{self.version}"

    @property
    def repository_path(self) -> str:
        group_path = self.group.replace(".", "/")
        return f"{group_path}/{self.name}/{self.version}/{self.artifact_name}"


@dataclass(frozen=True)
class RepositoryResult:
    repository: str
    sha256: str | None
    source: str


@dataclass
class ArtifactVerification:
    checksum: ArtifactChecksum
    repository_results: dict[str, RepositoryResult] = field(default_factory=dict)


def read_generated_checksums(metadata_path: Path) -> list[ArtifactChecksum]:
    root = ElementTree.parse(metadata_path).getroot()
    generated_checksums = []

    for component in root.findall(".//{*}component"):
        group = required_attribute(component, "group")
        name = required_attribute(component, "name")
        version = required_attribute(component, "version")

        for artifact in component.findall("{*}artifact"):
            artifact_name = required_attribute(artifact, "name")
            for sha256 in artifact.findall("{*}sha256"):
                if sha256.get("origin") != GENERATED_ORIGIN:
                    continue

                expected_sha256 = required_attribute(sha256, "value").lower()
                if not SHA256_PATTERN.fullmatch(expected_sha256):
                    raise ValueError(
                        f"Invalid SHA-256 for {group}:{name}:{version} ({artifact_name})"
                    )

                generated_checksums.append(
                    ArtifactChecksum(
                        group, name, version, artifact_name, expected_sha256
                    )
                )

    return generated_checksums


def required_attribute(element: ElementTree.Element, attribute: str) -> str:
    value = element.get(attribute)
    if value is None:
        raise ValueError(f"Missing '{attribute}' attribute on <{element.tag}>")
    return value


def get_artifact_sha256(
    repository: str, base_url: str, artifact_path: str
) -> RepositoryResult:
    sha256_url = f"{base_url}/{artifact_path}.sha256"
    try:
        content = download(sha256_url, timeout=5).decode("utf-8").strip()
        published_sha256 = content.split()[0].lower()
        if SHA256_PATTERN.fullmatch(published_sha256):
            return RepositoryResult(repository, published_sha256, "Published .sha256")
    except (
        IndexError,
        UnicodeDecodeError,
        OSError,
        http.client.HTTPException,
    ):
        pass

    artifact_url = f"{base_url}/{artifact_path}"
    try:
        artifact = download(artifact_url, timeout=10)
        calculated_sha256 = hashlib.sha256(artifact).hexdigest()
        return RepositoryResult(
            repository, calculated_sha256, "Calculated from artifact"
        )
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return RepositoryResult(repository, None, "Not found")
        return RepositoryResult(repository, None, f"HTTP {error.code}")
    except urllib.error.URLError as error:
        return RepositoryResult(repository, None, f"Unavailable: {error.reason}")
    except (OSError, http.client.HTTPException) as error:
        return RepositoryResult(repository, None, f"Unavailable: {error!r}")


def download(url: str, timeout: int) -> bytes:
    request = urllib.request.Request(
        url, headers={"User-Agent": "m2-sha256-verifier/1.0"}
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def verify_checksums(checksums: list[ArtifactChecksum]) -> bool:
    verifications = fetch_repository_results(checksums)
    verified_count = 0
    mismatched_count = 0
    unverifiable_count = 0

    for verification in verifications:
        checksum = verification.checksum
        print(f"\n{checksum.coordinate} ({checksum.artifact_name})")
        print(f"  Reported checksum: {checksum.expected_sha256}")
        has_match = False
        has_mismatch = False

        for repository in REPOSITORIES:
            result = verification.repository_results[repository]
            if result.sha256 is None:
                print(f"  [--] {result.repository:<20} {result.source}")
                continue

            if result.sha256 == checksum.expected_sha256:
                print(
                    f"  [OK] {result.repository:<20} {result.sha256} ({result.source})"
                )
                has_match = True
            else:
                print(
                    f"  [!!] {result.repository:<20} {result.sha256} "
                    f"(expected {checksum.expected_sha256})"
                )
                has_mismatch = True

        if has_match and not has_mismatch:
            verified_count += 1
            print("  Result: VERIFIED")
        elif has_mismatch:
            mismatched_count += 1
            print("  Result: FAILED (checksum mismatch)")
        else:
            unverifiable_count += 1
            print("  Result: UNVERIFIABLE (no repository returned a checksum)")

    print(
        f"\nSummary: {verified_count} verified, {mismatched_count} mismatched, "
        f"{unverifiable_count} unverifiable"
    )
    return mismatched_count == 0 and unverifiable_count == 0


def fetch_repository_results(
    checksums: list[ArtifactChecksum],
) -> list[ArtifactVerification]:
    verifications = [ArtifactVerification(checksum) for checksum in checksums]
    max_workers = min(12, len(checksums) * len(REPOSITORIES))

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {}
        for verification in verifications:
            for repository, base_url in REPOSITORIES.items():
                future = executor.submit(
                    get_artifact_sha256,
                    repository,
                    base_url,
                    verification.checksum.repository_path,
                )
                futures[future] = verification

        for future in as_completed(futures):
            verification = futures[future]
            result = future.result()
            verification.repository_results[result.repository] = result

    return verifications


def main() -> int:
    try:
        checksums = read_generated_checksums(METADATA_PATH)
    except (OSError, ElementTree.ParseError, ValueError) as error:
        print(f"Failed to read {METADATA_PATH}: {error}", file=sys.stderr)
        return 1

    if not checksums:
        print(
            f"No checksums with origin '{GENERATED_ORIGIN}' found in {METADATA_PATH}"
        )
        return 0

    print(f"Verifying {len(checksums)} generated checksums from {METADATA_PATH}")
    return 0 if verify_checksums(checksums) else 1


if __name__ == "__main__":
    sys.exit(main())
