name: Prepare Next Development Iteration

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: Version number of the next iteration
        required: true

jobs:
  Next-Iteration-Job:
    name: Next Iteration Job
    runs-on: ubuntu-latest-large
    permissions:
      pull-requests: write
      contents: write

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Update Version Number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          BRANCH="gh-action/next-iteration.${{ github.run_id }}"
          git checkout -b "$BRANCH"
          # pushd integrationTests
          # mvn versions:set -DgenerateBackupPoms=false -DnewVersion="${{ inputs.nextVersion }}"
          # popd
          # sed --in-place "s/version=.*$/version=${{ inputs.nextVersion }}/" gradle.properties
          touch hello.txt
          git add hello.txt
          git commit -m "Prepare next development iteration ${{ inputs.nextVersion }}" -a
          git push --set-upstream origin "$BRANCH"
          gh pr create --base master --title "Prepare next development iteration ${{ inputs.nextVersion }}" --body ""
