name: Releasability status

on:
  workflow_dispatch:

jobs:
  update_releasability_status:
    runs-on: github-ubuntu-latest-s
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
